<a href="https://colab.research.google.com/github/quantumhome/DataAnalysisCaseStudy/blob/master/Linear_Algebra_handson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Good Morning, Everyone! 🌟

Welcome to today’s Linear Algebra Hands-On Session! 🎉
We’re thrilled to have you join us for this exciting journey into the world of matrices, vectors, and transformations. 📐🧮

💡 A Quick Reminder:
Please be interactive during the session! If you have any questions or doubts, don’t hesitate to ask in the chat box—we’re here to learn together. 💬✨

We’ll begin shortly as a few more learners are still joining. ⏳
 get ready to dive in!

Looking forward to an engaging and insightful session ahead! 🚀
Stay curious, and let’s make this a great learning experience. 🌟

#real life examples
netflix project---svd---singluar value decomposition

graphics

animations

pca-lda----principal component analysis,linear discriminant analysis


In [ ]:
#matrix
#add,sub,mul,div

In [ ]:
import numpy as np

In [ ]:
A = np.array([[1,2],[3,4]])
B= np.array([[5,6],[7,8]])

In [ ]:
C = A+B
C

array([[ 6,  8],
       [10, 12]])

In [ ]:
D = A - B
D

array([[-4, -4],
       [-4, -4]])

In [ ]:
E = A * B
E

array([[ 5, 12],
       [21, 32]])

In [ ]:
F = A / B
F

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
#dot product and cross product
dotA = np.dot(A,B)
dotA

array([[19, 22],
       [43, 50]])

In [ ]:
dotA = np.cross(A,B)
dotA

array([-4, -4])

In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20])
result = a+b
print(result)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [ ]:
#brodcasting of array---
one rule---what ever highest dimension exist we have change the other dimensio to the same as the higher one

In [ ]:
E = np.array([[2,1],[7,4]])--#find the inverse