<a href="https://colab.research.google.com/github/quantumhome/DataAnalysisCaseStudy/blob/master/Linear_Algebra_handson%20Aadhya%20mam%20file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Good Morning, Everyone! 🌟

Welcome to today’s Linear Algebra Hands-On Session! 🎉
We’re thrilled to have you join us for this exciting journey into the world of matrices, vectors, and transformations. 📐🧮

💡 A Quick Reminder:
Please be interactive during the session! If you have any questions or doubts, don’t hesitate to ask in the chat box—we’re here to learn together. 💬✨

We’ll begin shortly as a few more learners are still joining. ⏳
 get ready to dive in!

Looking forward to an engaging and insightful session ahead! 🚀
Stay curious, and let’s make this a great learning experience. 🌟

#real life examples
netflix project---svd---singluar value decomposition

graphics

animations

pca-lda----principal component analysis,linear discriminant analysis


In [ ]:
#matrix
#add,sub,mul,div

In [ ]:
import numpy as np

In [ ]:
A = np.array([[1,2],[3,4]])
B= np.array([[5,6],[7,8]])

In [ ]:
C = A+B
C

array([[ 6,  8],
       [10, 12]])

In [ ]:
D = A - B
D

array([[-4, -4],
       [-4, -4]])

In [ ]:
E = A * B
E

array([[ 5, 12],
       [21, 32]])

In [ ]:
F = A / B
F

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
#dot product and cross product
dotA = np.dot(A,B)
dotA

array([[19, 22],
       [43, 50]])

In [ ]:
dotA = np.cross(A,B)
dotA

array([-4, -4])

In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20])
result = a+b
print(result)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [ ]:
#brodcasting of array---
one rule---what ever highest dimension exist we have change the other dimensio to the same as the higher one

In [ ]:
from numpy.linalg import inv
E = np.array([[2,1],[7,4]])#--#find the inverse
X = inv(E)
X

array([[ 4., -1.],
       [-7.,  2.]])

In [ ]:
#pro: matrix power A^5
A = np.array([[1,2],[3,4]])
x = np.linalg.matrix_power(A, 5)
x

array([[1069, 1558],
       [2337, 3406]])

In [ ]:
a = np.array([[1,2],[3,4]])
y = a**5
y

array([[   1,   32],
       [ 243, 1024]])

In [ ]:
#orthogonal--- two vector are said t be orthogonal whenthey are perpendicular to each other
#when their dot product  as zero

In [ ]:
u = np.array([1,2,3])
v = np.array([3,-6,2])

#whether are they orthogonal
x = np.dot(u,v)
x

-3

In [ ]:
u = np.array([1,0,0])
v = np.array([0,1,0])

x = np.dot(u,v)
x

0

In [ ]:
#matrix decompostion
#breaking down the matrix into simpler matrix that can help to understand the patterns the solve yhe pblms easily
#lu---lower traiungle,upper traingle
#QR
lower triangle---abive diagnal all elements ate zero
upper-below diagonal all elements are zero

In [ ]:
from scipy.linalg import lu

In [ ]:
G = np.array([[4,3],[6,3]])
P,L,U =lu(G)
print(P)
print(L)
print(U)

[[0. 1.]
 [1. 0.]]
[[1.         0.        ]
 [0.66666667 1.        ]]
[[6. 3.]
 [0. 1.]]


In [ ]:
#QR---one matrix will be divided into componets orthogonal magrix---Q
#AND RIGHT ANGLE MATRIX

In [ ]:
from scipy.linalg import qr
G = np.array([[4,3],[6,3]])
Q, R =qr(G)
print(Q)
print(R)

[[-0.5547002  -0.83205029]
 [-0.83205029  0.5547002 ]]
[[-7.21110255 -4.16025147]
 [ 0.         -0.83205029]]


In [ ]:
#eigen values and eigen vectors
from numpy.linalg import eig
H = np.array([[5,4],[2,3]])

eigenvalues,eigenvectors = eig(H)
print(H)
print(eigenvalues)
print(eigenvectors)

[[5 4]
 [2 3]]
[7. 1.]
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [ ]:
Q =np.array([[-0.5547002 , -0.83205029],
 [-0.83205029 , 0.5547002 ]])

result = np.dot(Q, Q.T)
print(result)

[[ 9.99999997e-01 -1.62066738e-17]
 [-1.62066738e-17  9.99999997e-01]]
