<a href="https://colab.research.google.com/github/quantumhome/DataAnalysisCaseStudy/blob/master/Matrix_Hands_on_28_12_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np


In [6]:
A = np.array([[1, 2], [4, 5]])
B = np.array([[5,6], [7,8]])
# Addition
C= A + B
C

array([[ 6,  8],
       [11, 13]])

In [7]:
# substraction
D = A - B
D

array([[-4, -4],
       [-3, -3]])

In [8]:
# product
E = A * B
E

array([[ 5, 12],
       [28, 40]])

In [9]:
# division
F = A/B
F

array([[0.2       , 0.33333333],
       [0.57142857, 0.625     ]])

In [14]:
# dot prodcut and cross product

G = np.dot(A,B)
G
H = np.cross(A, B)
print(f"dot product is {G} and cross product is {H}")

dot product is [[19 22]
 [55 64]] and cross product is [-4 -3]
